# Generated by Django 4.0.6 on 2022-08-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkinInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя предмета')),
                ('steam_price', models.FloatField(verbose_name='Цена в стиме')),
                ('market_price', models.FloatField(verbose_name='Цена на маркете')),
                ('market_order', models.FloatField(verbose_name='Ордер на покупку на маркете')),
                ('buff_price', models.FloatField(verbose_name='Цена на баффе')),
                ('buff_order', models.FloatField(verbose_name='Цена ордера на баффе')),
                ('sb', models.FloatField(verbose_name='Отношение цены стима к баффу')),
                ('sm', models.FloatField(verbose_name='Отношение цены стима к маркету')),
                ('mb', models.FloatField(verbose_name='Отношение цены маркета к баффу')),
                ('ms', models.FloatField(verbose_name='Отношение цены маркета к стиму')),
                ('bm', models.FloatField(verbose_name='Отношение цены баффа к маркету')),
                ('bs', models.FloatField(verbose_name='Отношение цены баффа к стиму')),
                ('market_7d', models.IntegerField(blank=True, null=True, verbose_name='Количество покупок 7 дней на маркете')),
                ('num_sell_buff', models.IntegerField(blank=True, null=True, verbose_name='Количество предметов на баффе')),
                ('num_order_buff', models.IntegerField(blank=True, null=True, verbose_name='Количество ордеров на баффе')),
                ('buff_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на бафф')),
                ('market_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на маркет')),
                ('steam_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на стим')),
            ],
            options={
                'ordering': ['steam_price'],
            },
        ),
    ]
