# Generated by Django 4.0.6 on 2022-08-05 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csinf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_from', models.CharField(choices=[('S', 'steam'), ('M', 'market'), ('B', 'buff')], default='S', max_length=1)),
                ('sell_to', models.CharField(choices=[('S', 'steam'), ('M', 'market'), ('B', 'buff')], default='B', max_length=1)),
                ('buy_price', models.FloatField()),
                ('sell_price', models.FloatField()),
                ('text_notice', models.TextField(blank=True)),
                ('date_notice', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('skin_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='csinf.skininfo')),
            ],
        ),
    ]
