# Generated by Django 4.0.6 on 2022-08-06 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('csinf', '0004_notice_username_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='username_notice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
