# Generated by Django 4.0.6 on 2022-08-11 20:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csinf', '0005_alter_notice_username_notice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-date_notice']},
        ),
        migrations.AddField(
            model_name='notice',
            name='count_skins',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
